version: "3"

services:
  mongo:
    image: mongo:latest
    volumes:
      - codart_3_data:/data/db
      - codart_3_dataConfig:/data/configdb
      
  node:
    image: akshitgrover/codart_3:v1
    deploy:
      replicas: 2
    volumes:
      - codart_3_uploads:/app/uploads
    ports:
      - "3000:3000"
    links:
      - mongo

volumes:
  codart_3_uploads:
  codart_3_data:
  codart_3_dataConfig:
